feat(dstat): add --x-range flag

diff --git a/dstat/pdstat b/dstat/pdstat
--- a/dstat/pdstat
+++ b/dstat/pdstat
@@ -31,6 +31,7 @@ WIDTH=1400
 PLOT_XDATA='set xdata time'
 PLOT_TIMEFMT='set timefmt "%d/%m-%H:%M:%S"'
 PLOT_FORMAT_X='set format x "%H:%M:%S"'
+RANGE_X='0:100'
 
 clean_tempdir() {
   rm -rf "${TMP_DIR}"
@@ -73,6 +74,7 @@ Options:
   -o, --output <OUTPUT>           Output multiplot file [default: <FILE>.png]
   -p, --preview <BOOL>            Whether or not should open the multiplot after generation [default: true] [possible values: true, false]
   -t, --title <TITLE>             Multiplot title [default: dstat]
+  -x, --x-range <START>:<END>     Select/filter the range of data to plot in the x-axis [default: '0:100']
   -v, --verbose <BOOL>            Whether or not to be verbose [default: false] [possible values: true, false]
   -w, --width <WIDTH>             Multiplot width [default: 1400]
   -h, --help                      Print help information (use `--help` for more detail)
@@ -123,6 +125,9 @@ Options:
   -t, --title <TITLE>
           Multiplot title [default: dstat]
 
+  -x, --x-range <START>:<END>
+          Select/filter the range of data to plot in the x-axis [default: '0:100']
+
   -v, --verbose <BOOL>
           Whether or not to be verbose [default: false] [possible values: true, false]
 
@@ -169,6 +174,13 @@ error_no_input() {
   exit 1
 }
 
+error_x_range() {
+  error="${1}"
+  printf 1>&2 "%s ...\n" "${error}"
+  printf 1>&2 "\nFor more information try '--help'\n"
+  exit 1
+}
+
 error_preview() {
   printf 1>&2 "the flag --preview <BOOL> must be 'true' or 'false' ...\n"
   printf 1>&2 "\nFor more information try '--help'\n"
@@ -209,7 +221,7 @@ deps_validate() {
 
 args_parse() {
   local args
-  if ! args=$(getopt -a -n dstat -o ho:v:f:g:l:p:s:t:w: --long help,preview:,verbose:,output:,width:,height:,font:,title:,font-scale:,line-width:,color-fg:,color-bg: -- "$@"); then
+  if ! args=$(getopt -a -n dstat -o ho:v:f:g:l:p:s:t:w:x: --long help,preview:,verbose:,output:,width:,height:,font:,title:,font-scale:,line-width:,color-fg:,color-bg:,x-range: -- "$@"); then
     printf 1>&2 "\nFor more information try '--help'\n"
     exit 1
   fi
@@ -253,6 +265,10 @@ args_parse() {
       shift
       COLOR_BG="$1"
       ;;
+    -x | --x-range)
+      shift
+      RANGE_X="$1"
+      ;;
     -p | --preview)
       shift
       PREVIEW_PLOT="$1"
@@ -282,6 +298,30 @@ args_parse() {
   if [[ -z "${FILE}" ]]; then
     error_no_input
   fi
+}
+
+arg_x_range() {
+  if ! range=$(echo "${RANGE_X}" | rg '^\d{1,3}:\d{1,3}$'); then
+    error_x_range "the value '<START>:<END>' for the flag --x-range must match the regex '^\d{1,3}:\d{1,3}$'"
+  fi
+
+  range_x_start=$(echo "${range}" | awk -F ':' '{print $1}')
+  range_x_end=$(echo "${range}" | awk -F ':' '{print $2}')
+
+  if [[ $(echo "${range_x_start} >= ${range_x_end}" | bc) == 1 ]]; then
+    error_x_range "the values '<START>:<END>' for the flag --x-range must respect that '<START>' is smaller than '<END>'"
+  fi
+
+  if [[ $(echo "${range_x_start} < 0" | bc) == 1 ]]; then
+    error_x_range "the values '<START>:<END>' for the flag --x-range must respect that '<START>' is equal or greater than 0"
+  fi
+
+  if [[ $(echo "${range_x_end} > 100" | bc) == 1 ]]; then
+    error_x_range "the values '<START>:<END>' for the flag --x-range must respect that '<END>' is equal or smaller than 100"
+  fi
+
+  RANGE_X_START="${range_x_start}"
+  RANGE_X_END="${range_x_end}"
 }
 
 arg_preview() {
@@ -322,6 +362,7 @@ args_validate() {
   arg_preview
   arg_verbose
   arg_output
+  arg_x_range
 }
 
 calc_font_size() {
@@ -1042,6 +1083,24 @@ dstat_to_csv() {
   fi
 }
 
+calc_x_range() {
+  PLOT_RANGE_X_START="$(map_range "${RANGE_X_START}")"
+  PLOT_RANGE_X_END="$(map_range "${RANGE_X_END}")"
+}
+
+map_range() {
+  input="${1}"
+  output_start=2
+  output_end=$(wc -l "${CSV_NUMFMT}" | awk '{print $1}' | bc)
+  input_start=0
+  input_end=100
+
+  slope="(${output_end} - ${output_start}) / (${input_end} - ${input_start})"
+  output="${output_start} + ${slope} * (${input} - ${input_start})"
+  line=$(echo "${output}" | bc)
+  rg . "${CSV_NUMFMT}" --line-number | rg "^${line}:" | sd "^${line}:(.+)" '$1' | awk -F',' '{print $1}'
+}
+
 plot_draw() {
   height=$(echo "${multiplot_layout_lines} * ${HEIGHT}" | bc)
 
@@ -1080,6 +1139,7 @@ set style line 4 linecolor rgb '#44c51b8a' linetype 1 linewidth ${LINE_WIDTH} po
 set style line 5 linecolor rgb '#44756bb1' linetype 1 linewidth ${LINE_WIDTH} pointtype 1 pointsize 1
 
 set border back
+set xrange ["${PLOT_RANGE_X_START}":"${PLOT_RANGE_X_END}"]
 
 set title "Load Average" font "${FONT}-Bold,$(calc_font_size 18)"
 $(echo "${plot_load_avg}")
@@ -1171,6 +1231,7 @@ main() {
   deps_validate
   mktempdir
   dstat_to_csv
+  calc_x_range
   plot_draw
   plot_preview
 }
